inherit_from: .rubocop_todo.yml

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - 'app/controllers/comments_controller.rb'

  Enabled: false
