name: Test

on:
  push:
    branches:
      - dev
      - test
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
    - name: Clear GitHub Actions cache
      run: |
        npm cache clean --force
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.20.2'  # Set the Node.js version you want here!
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.5
        bundler-cache: true

    - name: Install PostgreSQL client
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3



    - name: Setup DB
      env:
        REDIS_URL: redis://localhost:6379/0
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres
        RAILS_ENV: test
      run: |
        bundle exec rails db:setup RAILS_ENV=test
        bundle exec rake db:migrate RAILS_ENV=test


    - name: Run Tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres
        RAILS_ENV: test
      run: |
        bundler exec rspec

#    - name: Run rubocop
#      run: bundler exec rubocop --force-exclusion vendor/*/** --out rubocop.txt
    - name: Upload coverage results
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: coverage-report
        path: coverage
#    - name: Upload rubocop report
#      uses: actions/upload-artifact@master
#      if: always()
#      with:
#        name: rubocop-report.txt
#        path: rubocop.txt
